
import { PokemonItem } from "../../../../interfaces/pokemon-item";

export const legendaryByGeneration: Record<number, PokemonItem[]> = {
  1: [
    { text: "pokemon.articuno", pokemonId: 144, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.zapdos", pokemonId: 145, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.moltres", pokemonId: 146, fillStyle: "darkorange", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.mewtwo", pokemonId: 150, fillStyle: "purple", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.mew", pokemonId: 151, fillStyle: "pink", sprite: null, shiny: false, power: 5, weight: 1 }],
  2: [
    { text: "pokemon.raikou", pokemonId: 243, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.entei", pokemonId: 244, fillStyle: "brown", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.suicune", pokemonId: 245, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.lugia", pokemonId: 249, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.ho-oh", pokemonId: 250, fillStyle: "darkred", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.celebi", pokemonId: 251, fillStyle: "green", sprite: null, shiny: false, power: 5, weight: 1 }],
  3: [
    { text: "pokemon.regirock", pokemonId: 377, fillStyle: "brown", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.regice", pokemonId: 378, fillStyle: "darkcyan", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.registeel", pokemonId: 379, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.latias", pokemonId: 380, fillStyle: "darkred", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.latios", pokemonId: 381, fillStyle: "darkcyan", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.kyogre", pokemonId: 382, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.groudon", pokemonId: 383, fillStyle: "darkred", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.rayquaza", pokemonId: 384, fillStyle: "green", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.jirachi", pokemonId: 385, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.deoxys", pokemonId: 386, fillStyle: "darkred", sprite: null, shiny: false, power: 5, weight: 1 }],
  4: [
    { text: "pokemon.uxie", pokemonId: 480, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.mesprit", pokemonId: 481, fillStyle: "pink", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.azelf", pokemonId: 482, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.dialga", pokemonId: 483, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.palkia", pokemonId: 484, fillStyle: "purple", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.heatran", pokemonId: 485, fillStyle: "brown", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.regigigas", pokemonId: 486, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.giratina", pokemonId: 487, fillStyle: "black", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.cresselia", pokemonId: 488, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.phione", pokemonId: 489, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.manaphy", pokemonId: 490, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.darkrai", pokemonId: 491, fillStyle: "black", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.shaymin", pokemonId: 492, fillStyle: "green", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.arceus", pokemonId: 493, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 }],
  5: [
    { text: "pokemon.victini", pokemonId: 494, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.cobalion", pokemonId: 638, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.terrakion", pokemonId: 639, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.virizion", pokemonId: 640, fillStyle: "green", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.tornadus", pokemonId: 641, fillStyle: "green", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.thundurus", pokemonId: 642, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.reshiram", pokemonId: 643, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.zekrom", pokemonId: 644, fillStyle: "black", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.landorus", pokemonId: 645, fillStyle: "brown", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.kyurem", pokemonId: 646, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.keldeo", pokemonId: 647, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.meloetta", pokemonId: 648, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.genesect", pokemonId: 649, fillStyle: "purple", sprite: null, shiny: false, power: 5, weight: 1 }],
  6: [
    { text: "pokemon.xerneas", pokemonId: 716, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.yveltal", pokemonId: 717, fillStyle: "darkred", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.zygarde", pokemonId: 718, fillStyle: "green", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.diancie", pokemonId: 719, fillStyle: "pink", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.hoopa", pokemonId: 720, fillStyle: "purple", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.volcanion", pokemonId: 721, fillStyle: "brown", sprite: null, shiny: false, power: 5, weight: 1 }],
  7: [
    { text: "pokemon.silvally", pokemonId: 773, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.tapu-koko", pokemonId: 785, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.tapu-lele", pokemonId: 786, fillStyle: "pink", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.tapu-bulu", pokemonId: 787, fillStyle: "darkred", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.tapu-fini", pokemonId: 788, fillStyle: "purple", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.cosmog", pokemonId: 789, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.cosmoem", pokemonId: 790, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.solgaleo", pokemonId: 791, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.lunala", pokemonId: 792, fillStyle: "purple", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.necrozma", pokemonId: 800, fillStyle: "black", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.magearna", pokemonId: 801, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.marshadow", pokemonId: 802, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.zeraora", pokemonId: 807, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.meltan", pokemonId: 808, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
    { text: "pokemon.melmetal", pokemonId: 809, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 }],
  8: [
    { text: "pokemon.zacian", pokemonId: 888, fillStyle: "darkblue", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.zamazenta", pokemonId: 889, fillStyle: "darkred", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.eternatus", pokemonId: 890, fillStyle: "purple", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.kubfu", pokemonId: 891, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
    { text: "pokemon.urshifu", pokemonId: 892, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.zarude", pokemonId: 893, fillStyle: "green", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.regieleki", pokemonId: 894, fillStyle: "goldenrod", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.regidrago", pokemonId: 895, fillStyle: "green", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.glastrier", pokemonId: 896, fillStyle: "gray", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.spectrier", pokemonId: 897, fillStyle: "black", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.calyrex", pokemonId: 898, fillStyle: "green", sprite: null, shiny: false, power: 5, weight: 1 },
    { text: "pokemon.enamorus", pokemonId: 905, fillStyle: "pink", sprite: null, shiny: false, power: 5, weight: 1 }]
}
