import { PokemonItem } from "../../../../interfaces/pokemon-item";

export const cavePokemonByGeneration: Record<number, PokemonItem[]> = {
    1: [
        { text: "pokemon.arbok", pokemonId: 24, fillStyle: "purple", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.sandslash", pokemonId: 28, fillStyle: "goldenrod", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.clefairy", pokemonId: 35, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.zubat", pokemonId: 41, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.golbat", pokemonId: 42, fillStyle: "purple", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.paras", pokemonId: 46, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.parasect", pokemonId: 47, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.diglett", pokemonId: 50, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.dugtrio", pokemonId: 51, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.psyduck", pokemonId: 54, fillStyle: "goldenrod", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.golduck", pokemonId: 55, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.primeape", pokemonId: 57, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.kadabra", pokemonId: 64, fillStyle: "brown", sprite:null , shiny:false , power :2 , weight :1},
        { text:"pokemon.machop" , pokemonId :66 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.machoke" , pokemonId :67 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.geodude" , pokemonId :74 , fillStyle :"brown" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.graveler", pokemonId: 75, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.slowpoke", pokemonId: 79, fillStyle: "pink", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.slowbro", pokemonId: 80, fillStyle: "pink", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.magneton", pokemonId: 82, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.seel" , pokemonId :86 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.dewgong" , pokemonId :87 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.onix" , pokemonId :95 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.electrode" , pokemonId :101 , fillStyle :"darkred" , sprite :null , shiny:false , power :3 , weight :1},
        { text:"pokemon.marowak" , pokemonId :105 , fillStyle :"brown" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.ditto" , pokemonId :132 , fillStyle :"purple" , sprite:null, shiny:false,power :1,weight :1}
    ],
    2: [
        { text: "pokemon.rattata", pokemonId: 19, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.raticate", pokemonId: 20, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.sandshrew", pokemonId: 27, fillStyle: "goldenrod", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.zubat", pokemonId: 41, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.golbat", pokemonId: 42, fillStyle: "purple", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.golduck" , pokemonId :55 , fillStyle :"darkblue" , sprite :null , shiny:false , power :3 , weight :1},
        { text: "pokemon.machop", pokemonId: 66, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.machoke", pokemonId: 67, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.geodude", pokemonId: 74, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.graveler" , pokemonId :75 , fillStyle :"brown" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.seel" , pokemonId :86 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.onix" , pokemonId :95 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.krabby" , pokemonId :98 , fillStyle :"darkred" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.kingler" , pokemonId :99 , fillStyle :"darkred" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.jynx" , pokemonId :124, fillStyle :"darkred", sprite:null, shiny:false,power :2,weight :1},
        { text:"pokemon.marill" , pokemonId :183, fillStyle :"darkblue", sprite:null, shiny:false,power :2,weight :1},
        { text: "pokemon.wooper", pokemonId: 194, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.quagsire", pokemonId: 195, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.misdreavus", pokemonId: 200, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.unown", pokemonId: 201, fillStyle: "black", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.wobbuffet" , pokemonId :202 , fillStyle :"darkblue" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.dunsparce" , pokemonId :206 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.steelix" , pokemonId :208 , fillStyle :"gray" , sprite :null , shiny:false , power :3 , weight :1},
        { text:"pokemon.sneasel" , pokemonId :215 , fillStyle :"black" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.teddiursa" , pokemonId :216 , fillStyle :"brown" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.ursaring" , pokemonId :217 , fillStyle :"brown" , sprite :null , shiny:false , power :3 , weight :1},
        { text: "pokemon.swinub", pokemonId: 220, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.delibird", pokemonId: 225, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.phanpy", pokemonId: 231, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.donphan", pokemonId: 232, fillStyle: "gray", sprite: null, shiny: false, power: 3, weight: 1 },
        { text:"pokemon.larvitar" , pokemonId :246 , fillStyle :"green" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.pupitar" , pokemonId :247 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1}    
    ],
    3: [
        { text:"pokemon.zubat" , pokemonId :41 , fillStyle :"purple" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.golbat" , pokemonId :42 , fillStyle :"purple" , sprite :null , shiny:false , power :2 , weight :1},
        { text: "pokemon.abra", pokemonId: 63, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.machop", pokemonId: 66, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.geodude", pokemonId: 74, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.graveler", pokemonId: 75, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.grimer" , pokemonId :88 , fillStyle :"purple" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.koffing" , pokemonId :109 , fillStyle :"purple" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.ditto" , pokemonId :132 , fillStyle :"purple" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.ariados" , pokemonId :168 , fillStyle :"darkred" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.mareep" , pokemonId :179 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.aipom" , pokemonId :190 , fillStyle :"purple" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.pineco", pokemonId: 204, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.shuckle", pokemonId: 213, fillStyle: "goldenrod", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.teddiursa", pokemonId: 216, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.slugma", pokemonId: 218, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.houndour" , pokemonId :228 , fillStyle :"black" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.stantler" , pokemonId :234 , fillStyle :"brown" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.smeargle" , pokemonId :235 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.whismur" , pokemonId :293 , fillStyle :"pink" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.loudred" , pokemonId :294 , fillStyle :"darkblue" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.makuhita" , pokemonId :296 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.hariyama", pokemonId: 297, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.nosepass", pokemonId: 299, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.sableye", pokemonId: 302, fillStyle: "purple", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.mawile", pokemonId: 303, fillStyle: "black", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.aron" , pokemonId :304 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.lairon" , pokemonId :305 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.medicham" , pokemonId :308 , fillStyle :"darkred" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.numel" , pokemonId :322 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.torkoal" , pokemonId :324 , fillStyle :"brown" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.trapinch" , pokemonId :328 , fillStyle :"brown" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.swablu", pokemonId: 333, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.lunatone", pokemonId: 337, fillStyle: "goldenrod", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.solrock", pokemonId: 338, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.claydol", pokemonId: 344, fillStyle: "black", sprite: null, shiny: false, power: 3, weight: 1 },
        { text:"pokemon.snorunt" , pokemonId :361 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.spheal" , pokemonId :363 , fillStyle :"darkblue" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.sealeo" , pokemonId :364 , fillStyle :"darkblue" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.bagon" , pokemonId :371 , fillStyle :"darkblue" , sprite :null , shiny:false , power :1 , weight :1}
    ],
    4: [
        { text: "pokemon.clefairy", pokemonId: 35, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.zubat", pokemonId: 41, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.golbat", pokemonId: 42, fillStyle: "purple", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.psyduck", pokemonId: 54, fillStyle: "goldenrod", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.golduck", pokemonId: 55, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
        { text:"pokemon.kadabra" , pokemonId :64 , fillStyle :"brown" , sprite :null , shiny:false , power :2 , weight :1},
        { text: "pokemon.machop", pokemonId: 66, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.machoke", pokemonId: 67, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.geodude", pokemonId: 74, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.graveler", pokemonId: 75, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.onix" , pokemonId :95 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.weezing" , pokemonId :110 , fillStyle :"purple" , sprite :null , shiny:false , power :3 , weight :1},
        { text:"pokemon.rhyhorn" , pokemonId :111 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.rhydon" , pokemonId :112 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.cleffa" , pokemonId :173 , fillStyle :"pink" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.unown" , pokemonId :201 , fillStyle :"black" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.steelix", pokemonId: 208, fillStyle: "gray", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.sneasel", pokemonId: 215, fillStyle: "black", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.slugma", pokemonId: 218, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.magcargo", pokemonId: 219, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.meditite" , pokemonId :307 , fillStyle :"darkblue" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.medicham" , pokemonId :308 , fillStyle :"darkred" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.numel" , pokemonId :322 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.camerupt" , pokemonId :323 , fillStyle :"darkred" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.chimecho" , pokemonId :358 , fillStyle :"darkblue" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.floatzel" , pokemonId :419 , fillStyle :"brown" , sprite :null , shiny:false , power :3 , weight :1},
        { text: "pokemon.chingling", pokemonId: 433, fillStyle: "goldenrod", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.bronzor", pokemonId: 436, fillStyle: "green", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.bronzong", pokemonId: 437, fillStyle: "green", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.hippopotas", pokemonId: 449, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.snover", pokemonId: 459, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.abomasnow" , pokemonId :460 , fillStyle :"gray" , sprite :null , shiny:false , power :3 , weight :1}    
    ],
    5: [
        { text: "pokemon.rattata", pokemonId: 19, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.raticate", pokemonId: 20, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.golduck", pokemonId: 55, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.geodude", pokemonId: 74, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.graveler", pokemonId: 75, fillStyle: "brown", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.seel" , pokemonId :86 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.onix", pokemonId: 95, fillStyle: "gray", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.lickitung", pokemonId: 108, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.steelix", pokemonId: 208, fillStyle: "gray", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.shuckle", pokemonId: 213, fillStyle: "goldenrod", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.nosepass", pokemonId: 299, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.sableye" , pokemonId :302 , fillStyle :"purple" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.mawile" , pokemonId :303 , fillStyle :"black" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.aron" , pokemonId :304 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.lairon" , pokemonId :305 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.numel" , pokemonId :322 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.camerupt", pokemonId: 323, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.spoink", pokemonId: 325, fillStyle: "black", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.grumpig", pokemonId: 326, fillStyle: "purple", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.banette", pokemonId: 354, fillStyle: "black", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.riolu" , pokemonId :447 , fillStyle :"darkblue" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.skorupi" , pokemonId :451 , fillStyle :"purple" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.roggenrola" , pokemonId :524 , fillStyle :"darkblue" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.boldore", pokemonId: 525, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.woobat", pokemonId: 527, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.drilbur", pokemonId: 529, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.excadrill", pokemonId: 530, fillStyle: "gray", sprite: null, shiny: false, power: 3, weight: 1 },
        { text:"pokemon.timburr" , pokemonId :532 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.gurdurr" , pokemonId :533 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.crustle" , pokemonId :558 , fillStyle :"darkred" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.joltik" , pokemonId :595 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.ferroseed" , pokemonId :597 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.klink" , pokemonId :599 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.tynamo", pokemonId: 602, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.eelektrik", pokemonId: 603, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.axew", pokemonId: 610, fillStyle: "green", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.cubchoo", pokemonId: 613, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.beartic", pokemonId: 614, fillStyle: "gray", sprite: null, shiny: false, power: 3, weight: 1 },
        { text:"pokemon.cryogonal" , pokemonId :615 , fillStyle :"darkblue" , sprite :null , shiny:false , power :3 , weight :1},
        { text: "pokemon.mienfoo", pokemonId: 619, fillStyle: "goldenrod", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.druddigon", pokemonId: 621, fillStyle: "darkred", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.golurk", pokemonId: 623, fillStyle: "green", sprite: null, shiny: false, power: 3, weight: 1 },
        { text:"pokemon.heatmor" , pokemonId :631 , fillStyle :"darkred" , sprite :null , shiny:false , power :3 , weight :1},
        { text:"pokemon.durant" , pokemonId :632 , fillStyle :"gray" , sprite :null , shiny:false , power :3 , weight :1},
        { text:"pokemon.deino" , pokemonId :633 , fillStyle :"darkblue" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.zweilous" , pokemonId :634 , fillStyle :"darkblue" , sprite :null , shiny:false , power :2 , weight :1}
    ],
    6: [
        { text:"pokemon.sandslash" , pokemonId :28 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :2 , weight :1},
        { text: "pokemon.zubat", pokemonId: 41, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.machop", pokemonId: 66, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.geodude", pokemonId: 74, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.graveler" , pokemonId :75 , fillStyle :"brown" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.haunter" , pokemonId :93 , fillStyle :"purple" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.onix" , pokemonId :95 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.cubone" , pokemonId :104 , fillStyle :"brown" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.lickitung" , pokemonId :108 , fillStyle :"pink" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.rhyhorn" , pokemonId :111 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.kangaskhan" , pokemonId :115 , fillStyle :"brown" , sprite:null, shiny:false, power:3, weight:1},
        { text: "pokemon.mr.mime", pokemonId: 122, fillStyle: "pink", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.jynx", pokemonId: 124, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.ariados", pokemonId: 168, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.wobbuffet", pokemonId: 202, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.shuckle" , pokemonId :213 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :3 , weight :1},
        { text:"pokemon.piloswine" , pokemonId :221 , fillStyle :"brown" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.smoochum" , pokemonId :238 , fillStyle :"pink" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.larvitar" , pokemonId :246 , fillStyle :"green" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.pupitar" , pokemonId :247 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.whismur" , pokemonId :293 , fillStyle :"pink" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.sableye", pokemonId: 302, fillStyle: "purple", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.mawile", pokemonId: 303, fillStyle: "black", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.aron", pokemonId: 304, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.lairon" , pokemonId :305 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.meditite" , pokemonId :307 , fillStyle :"darkblue" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.lunatone" , pokemonId :337 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :2 , weight :1},
        { text: "pokemon.solrock", pokemonId: 338, fillStyle: "darkred", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.floatzel", pokemonId: 419, fillStyle: "brown", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.chingling", pokemonId: 433, fillStyle: "goldenrod", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.mime.jr" , pokemonId :439 , fillStyle :"pink" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.roggenrola" , pokemonId :524 , fillStyle :"darkblue" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.woobat" , pokemonId :527 , fillStyle :"darkblue" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.gurdurr" , pokemonId :533 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.dwebble" , pokemonId :557 , fillStyle :"darkred" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.solosis" , pokemonId :577 , fillStyle :"green" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.vanillite" , pokemonId :582 , fillStyle :"gray" , sprite :null , shiny:false , power :1, weight :1},
        { text: "pokemon.Ferroseed", pokemonId: 597, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.axew", pokemonId: 610, fillStyle: "green", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.cubchoo", pokemonId: 613, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.beartic", pokemonId: 614, fillStyle: "gray", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.cryogonal", pokemonId: 615, fillStyle: "darkblue", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.druddigon", pokemonId: 621, fillStyle: "darkred", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.durant", pokemonId: 632, fillStyle: "gray", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.zweilous", pokemonId: 634, fillStyle: "darkblue", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.carbink", pokemonId: 703, fillStyle: "gray", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.bergmite", pokemonId: 712, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.noibat", pokemonId: 714, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 }
    ],
    7: [
        { text: "pokemon.sandshrew", pokemonId: 27, fillStyle: "goldenrod", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.vulpix", pokemonId: 37, fillStyle: "brown", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.zubat", pokemonId: 41, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.golbat", pokemonId: 42, fillStyle: "purple", sprite: null, shiny: false, power: 2, weight: 1 },
        { text:"pokemon.diglett" , pokemonId :50 , fillStyle :"brown" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.dugtrio" , pokemonId :51 , fillStyle :"brown" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.psyduck" , pokemonId :54 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :1 , weight :1},
        { text: "pokemon.seel", pokemonId: 86, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.crobat", pokemonId: 169, fillStyle: "purple", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.sneasel", pokemonId: 215, fillStyle: "black", sprite: null, shiny: false, power: 2, weight: 1 },
        { text: "pokemon.delibird", pokemonId: 225, fillStyle: "darkred", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.smoochum" , pokemonId :238 , fillStyle :"pink" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.larvitar" , pokemonId :246 , fillStyle :"green" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.sableye" , pokemonId :302 , fillStyle :"purple" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.mawile" , pokemonId :303 , fillStyle :"black" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.absol" , pokemonId :359 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.glalie" , pokemonId :362 , fillStyle :"gray" , sprite :null , shiny:false , power :2 , weight :1},
        { text: "pokemon.happiny", pokemonId: 440, fillStyle: "pink", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.roggenrola", pokemonId: 524, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.druddigon", pokemonId: 621, fillStyle: "darkred", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.carbink", pokemonId: 703, fillStyle: "gray", sprite: null, shiny: false, power: 3, weight: 1 },
        { text: "pokemon.noivern", pokemonId: 715, fillStyle: "purple", sprite: null, shiny: false, power: 3, weight: 1 },
        { text:"pokemon.drampa" , pokemonId :780 , fillStyle :"gray" , sprite :null , shiny:false , power :3 , weight :1}
    ],
    8: [
        { text:"pokemon.diglett" , pokemonId :50 , fillStyle :"brown" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.shuckle" , pokemonId :213 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :3 , weight :1},
        { text: "pokemon.shellos", pokemonId: 422, fillStyle: "purple", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.croagunk", pokemonId: 453, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.woobat", pokemonId: 527, fillStyle: "darkblue", sprite: null, shiny: false, power: 1, weight: 1 },
        { text: "pokemon.drilbur", pokemonId: 529, fillStyle: "gray", sprite: null, shiny: false, power: 1, weight: 1 },
        { text:"pokemon.timburr" , pokemonId :532 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.scraggy" , pokemonId :559 , fillStyle :"goldenrod" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.stunfisk" , pokemonId :618 , fillStyle :"brown" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.binacle" , pokemonId :688 , fillStyle :"brown" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.noibat" , pokemonId :714 , fillStyle :"purple" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.wimpod" , pokemonId :767 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.chewtle" , pokemonId :833 , fillStyle :"green" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.drednaw" , pokemonId :834 , fillStyle :"green" , sprite :null , shiny:false , power :3 , weight :1},
        { text:"pokemon.rolycoly" , pokemonId :837 , fillStyle :"black" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.carkol" , pokemonId :838 , fillStyle :"black" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.coalossal" , pokemonId :839 , fillStyle :"black" , sprite :null , shiny:false , power :3 , weight :1},
        { text:"pokemon.pincurchin" , pokemonId :871 , fillStyle :"purple" , sprite :null , shiny:false , power :2 , weight :1},
        { text:"pokemon.zorua" , pokemonId :570 , fillStyle :"gray" , sprite :null , shiny:false , power :1 , weight :1},
        { text:"pokemon.zoroark" , pokemonId :571 , fillStyle :"gray" , sprite :null , shiny:false , power :3 , weight :1}
    ]
}