import { PokemonItem } from "../interfaces/pokemon-item";

export const legendaryByGeneration: Record<number, PokemonItem[]> = {
    1: [
        { text: "Articuno", pokemonId: 144, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Zapdos", pokemonId: 145, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Moltres", pokemonId: 146, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Mewtwo", pokemonId: 150, fillStyle: "purple", sprite: null, shiny: false, power: 5 },
        { text: "Mew", pokemonId: 151, fillStyle: "pink", sprite: null, shiny: false, power: 5 }],
    2: [
        { text: "Raikou", pokemonId: 243, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Entei", pokemonId: 244, fillStyle: "brown", sprite: null, shiny: false, power: 5 },
        { text: "Suicune", pokemonId: 245, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Lugia", pokemonId: 249, fillStyle: "white", sprite: null, shiny: false, power: 5 },
        { text: "Ho-oh", pokemonId: 250, fillStyle: "red", sprite: null, shiny: false, power: 5 },
        { text: "Celebi", pokemonId: 251, fillStyle: "green", sprite: null, shiny: false, power: 5 }],
    3: [
        { text: "Regirock", pokemonId: 377, fillStyle: "brown", sprite: null, shiny: false, power: 5 },
        { text: "Regice", pokemonId: 378, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Registeel", pokemonId: 379, fillStyle: "gray", sprite: null, shiny: false, power: 5 },
        { text: "Latias", pokemonId: 380, fillStyle: "red", sprite: null, shiny: false, power: 5 },
        { text: "Latios", pokemonId: 381, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Kyogre", pokemonId: 382, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Groudon", pokemonId: 383, fillStyle: "red", sprite: null, shiny: false, power: 5 },
        { text: "Rayquaza", pokemonId: 384, fillStyle: "green", sprite: null, shiny: false, power: 5 },
        { text: "Jirachi", pokemonId: 385, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Deoxys", pokemonId: 386, fillStyle: "red", sprite: null, shiny: false, power: 5 }],
    4: [
        { text: "Uxie", pokemonId: 480, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Mesprit", pokemonId: 481, fillStyle: "pink", sprite: null, shiny: false, power: 5 },
        { text: "Azelf", pokemonId: 482, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Dialga", pokemonId: 483, fillStyle: "white", sprite: null, shiny: false, power: 5 },
        { text: "Palkia", pokemonId: 484, fillStyle: "purple", sprite: null, shiny: false, power: 5 },
        { text: "Heatran", pokemonId: 485, fillStyle: "brown", sprite: null, shiny: false, power: 5 },
        { text: "Regigigas", pokemonId: 486, fillStyle: "white", sprite: null, shiny: false, power: 5 },
        { text: "Giratina", pokemonId: 487, fillStyle: "black", sprite: null, shiny: false, power: 5 },
        { text: "Cresselia", pokemonId: 488, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Phione", pokemonId: 489, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Manaphy", pokemonId: 490, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Darkrai", pokemonId: 491, fillStyle: "black", sprite: null, shiny: false, power: 5 },
        { text: "Shaymin", pokemonId: 492, fillStyle: "green", sprite: null, shiny: false, power: 5 },
        { text: "Arceus", pokemonId: 493, fillStyle: "white", sprite: null, shiny: false, power: 5 }],
    5: [
        { text: "Victini", pokemonId: 494, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Cobalion", pokemonId: 638, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Terrakion", pokemonId: 639, fillStyle: "gray", sprite: null, shiny: false, power: 5 },
        { text: "Virizion", pokemonId: 640, fillStyle: "green", sprite: null, shiny: false, power: 5 },
        { text: "Tornadus", pokemonId: 641, fillStyle: "green", sprite: null, shiny: false, power: 5 },
        { text: "Thundurus", pokemonId: 642, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Reshiram", pokemonId: 643, fillStyle: "white", sprite: null, shiny: false, power: 5 },
        { text: "Zekrom", pokemonId: 644, fillStyle: "black", sprite: null, shiny: false, power: 5 },
        { text: "Landorus", pokemonId: 645, fillStyle: "brown", sprite: null, shiny: false, power: 5 },
        { text: "Kyurem", pokemonId: 646, fillStyle: "gray", sprite: null, shiny: false, power: 5 },
        { text: "Keldeo", pokemonId: 647, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Meloetta", pokemonId: 648, fillStyle: "white", sprite: null, shiny: false, power: 5 },
        { text: "Genesect", pokemonId: 649, fillStyle: "purple", sprite: null, shiny: false, power: 5 }],
    6: [
        { text: "Xerneas", pokemonId: 716, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Yveltal", pokemonId: 717, fillStyle: "red", sprite: null, shiny: false, power: 5 },
        { text: "Zygarde", pokemonId: 718, fillStyle: "green", sprite: null, shiny: false, power: 5 },
        { text: "Diancie", pokemonId: 719, fillStyle: "pink", sprite: null, shiny: false, power: 5 },
        { text: "Hoopa", pokemonId: 720, fillStyle: "purple", sprite: null, shiny: false, power: 5 },
        { text: "Volcanion", pokemonId: 721, fillStyle: "brown", sprite: null, shiny: false, power: 5 }],
    7: [
        { text: "Silvally", pokemonId: 773, fillStyle: "gray", sprite: null, shiny: false, power: 5 },
        { text: "Tapu-koko", pokemonId: 785, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Tapu-lele", pokemonId: 786, fillStyle: "pink", sprite: null, shiny: false, power: 5 },
        { text: "Tapu-bulu", pokemonId: 787, fillStyle: "red", sprite: null, shiny: false, power: 5 },
        { text: "Tapu-fini", pokemonId: 788, fillStyle: "purple", sprite: null, shiny: false, power: 5 },
        { text: "Cosmog", pokemonId: 789, fillStyle: "blue", sprite: null, shiny: false, power: 1 },
        { text: "Cosmoem", pokemonId: 790, fillStyle: "blue", sprite: null, shiny: false, power: 2 },
        { text: "Solgaleo", pokemonId: 791, fillStyle: "white", sprite: null, shiny: false, power: 5 },
        { text: "Lunala", pokemonId: 792, fillStyle: "purple", sprite: null, shiny: false, power: 5 },
        { text: "Necrozma", pokemonId: 800, fillStyle: "black", sprite: null, shiny: false, power: 5 },
        { text: "Magearna", pokemonId: 801, fillStyle: "gray", sprite: null, shiny: false, power: 5 },
        { text: "Marshadow", pokemonId: 802, fillStyle: "gray", sprite: null, shiny: false, power: 5 },
        { text: "Zeraora", pokemonId: 807, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Meltan", pokemonId: 808, fillStyle: "gray", sprite: null, shiny: false, power: 1 },
        { text: "Melmetal", pokemonId: 809, fillStyle: "gray", sprite: null, shiny: false, power: 5 }],
    8: [
        { text: "Zacian", pokemonId: 888, fillStyle: "blue", sprite: null, shiny: false, power: 5 },
        { text: "Zamazenta", pokemonId: 889, fillStyle: "red", sprite: null, shiny: false, power: 5 },
        { text: "Eternatus", pokemonId: 890, fillStyle: "purple", sprite: null, shiny: false, power: 5 },
        { text: "Kubfu", pokemonId: 891, fillStyle: "gray", sprite: null, shiny: false, power: 2 },
        { text: "Urshifu", pokemonId: 892, fillStyle: "gray", sprite: null, shiny: false, power: 5 },
        { text: "Zarude", pokemonId: 893, fillStyle: "green", sprite: null, shiny: false, power: 5 },
        { text: "Regieleki", pokemonId: 894, fillStyle: "yellow", sprite: null, shiny: false, power: 5 },
        { text: "Regidrago", pokemonId: 895, fillStyle: "green", sprite: null, shiny: false, power: 5 },
        { text: "Glastrier", pokemonId: 896, fillStyle: "white", sprite: null, shiny: false, power: 5 },
        { text: "Spectrier", pokemonId: 897, fillStyle: "black", sprite: null, shiny: false, power: 5 },
        { text: "Calyrex", pokemonId: 898, fillStyle: "green", sprite: null, shiny: false, power: 5 },
        { text: "Enamorus", pokemonId: 905, fillStyle: "pink", sprite: null, shiny: false, power: 5 }]
}