export type GameState =
  | 'game-start'
  | 'starter-pokemon'
  | 'check-shininess'
  | 'start-adventure'
  | 'catch-pokemon'
  | 'evolve-pokemon'
  | 'select-from-pokemon-list'
  | 'select-evolution'
  | 'gym-battle'
  | 'game-over'
  | 'adventure-continues'
  | 'elite-four-preparation'
  | 'elite-four-battle'
  | 'champion-battle';