export const megaStoneItemNames = [
  'abomasnow-ite',
  'absol-ite',
  'aerodactyl-ite',
  'aggron-ite',
  'alakazam-ite',
  'altaria-ite',
  'ampharos-ite',
  'audino-ite',
  'banette-ite',
  'barbaracle-ite',
  'beedrill-ite',
  'blastoisinite',
  'blaziken-ite',
  'camerupt-ite',
  'charizardite-x',
  'charizardite-y',
  'clefable-ite',
  'diancie-ite',
  'dragalge-ite',
  'dragonite-ite',
  'feraligatr-ite',
  'gallade-ite',
  'garchomp-ite',
  'gardevoir-ite',
  'gengar-ite',
  'glalie-ite',
  'groudon-ite',
  'gyarados-ite',
  'heracross-ite',
  'houndoom-ite',
  'kangaskhan-ite',
  'kyogre-ite',
  'latias-ite',
  'latios-ite',
  'lopunny-ite',
  'lucario-ite',
  'manectric-ite',
  'mawile-ite',
  'medicham-ite',
  'meganium-ite',
  'metagross-ite',
  'mewtwo-ite',
  'pidgeot-ite',
  'pinsir-ite',
  'raichu-ite',
  'rayquaza-ite',
  'sableye-ite',
  'salamence-ite',
  'sceptile-ite',
  'scizor-ite',
  'sharpedo-ite',
  'skarmory-ite',
  'slowbro-ite',
  'starmie-ite',
  'steelix-ite',
  'swampert-ite',
  'tyranitar-ite',
  'venusaurite',
  'victreebel-ite',
  'zygardite'
  
] as const;

export type MegaStoneItemName = (typeof megaStoneItemNames)[number];

const megaStoneItemNameSet = new Set<string>(megaStoneItemNames);

export function isMegaStoneItemName(name: string): name is MegaStoneItemName {
  return megaStoneItemNameSet.has(name);
}