export const megaStoneItemNames = [
  'abomasite',
  'absolite',
  'absolite-z',
  'aerodactylite',
  'aggronite',
  'alakazite',
  'altarianite',
  'ampharosite',
  'audinite',
  'banettite',
  'barbaracite',
  'baxcalibrite',
  'beedrillite',
  'blastoisinite',
  'blazikenite',
  'cameruptite',
  'chandelurite',
  'charizardite-x',
  'charizardite-y',
  'chesnaughtite',
  'chimechite',
  'clefablite',
  'crabominite',
  'darkranite',
  'delphoxite',
  'diancite',
  'dragalgite',
  'dragoninite',
  'drampanite',
  'eelektrossite',
  'emboarite',
  'excadrite',
  'falinksite',
  'feraligite',
  'floettite',
  'froslassite',
  'galladite',
  'garchompite',
  'garchompite-z',
  'gardevoirite',
  'gengarite',
  'glalitite',
  'glimmoranite',
  'golisopite',
  'golurkite',
  'greninjite',
  'red-orb',
  'gyaradosite',
  'hawluchanite',
  'heatranite',
  'heracronite',
  'houndoominite',
  'kangaskhanite',
  'blue-orb',
  'latiasite',
  'latiosite',
  'lopunnite',
  'lucarionite',
  'lucarionite-z',
  'magearnite',
  'malamarite',
  'manectite',
  'mawilite',
  'medichamite',
  'meganiumite',
  'meowsticite',
  'metagrossite',
  'mewtwonite-x',
  'mewtwonite-y',
  'pidgeotite',
  'pinsirite',
  'pyroarite',
  'raichunite-x',
  'raichunite-y',
  'dragon-ascent',
  'sablenite',
  'salamencite',
  'sceptilite',
  'scizorite',
  'scolipite',
  'scovillainite',
  'scraftinite',
  'sharpedonite',
  'skarmorite',
  'slowbronite',
  'staraptite',
  'starminite',
  'steelixite',
  'swampertite',
  'tatsugirinite',
  'tyranitarite',
  'venusaurite',
  'victreebelite',
  'zeraorite',
  'zygardite'
  
] as const;

export type MegaStoneItemName = (typeof megaStoneItemNames)[number];

const megaStoneItemNameSet = new Set<string>(megaStoneItemNames);

export function isMegaStoneItemName(name: string): name is MegaStoneItemName {
  return megaStoneItemNameSet.has(name);
}